services:
  postgres:
    image: postgres:latest
    container_name: backend-postgres

    environment:
      POSTGRES_DB: primelar
      POSTGRES_USER: primelar
      POSTGRES_PASSWORD: secret

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/

volumes:
  postgres_data: