CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active        BOOLEAN       NOT NULL,
    created_ad    TIMESTAMP(6)  NOT NULL,
    email         VARCHAR(255)  NOT NULL,
    firstname     VARCHAR(255)  NOT NULL,
    lastname      VARCHAR(255),
    password_hash VARCHAR(255)  NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uq_roles_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS permissions (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uq_permissions_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS imoveis (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo         VARCHAR(255)   NOT NULL,
    descricao      TEXT,
    preco          NUMERIC(38, 2) NOT NULL,
    cidade         VARCHAR(255)   NOT NULL,
    bairro         VARCHAR(255)   NOT NULL,
    endereco       VARCHAR(255),
    quartos        INTEGER,
    banheiros      INTEGER,
    vagas          INTEGER,
    caminho_imagem VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    used       BOOLEAN      NOT NULL,
    user_id    BIGINT       NOT NULL,
    CONSTRAINT uq_prt_token    UNIQUE (token),
    CONSTRAINT fk_prt_user     FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS token_revogado (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token           VARCHAR(1000) NOT NULL,
    data_expiracao  TIMESTAMP(6),
    CONSTRAINT uq_token_revogado UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS favoritos (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT,
    imovel_id BIGINT,
    CONSTRAINT uq_favorito_user_imovel UNIQUE (user_id, imovel_id),
    CONSTRAINT fk_favorito_user        FOREIGN KEY (user_id)   REFERENCES users   (id),
    CONSTRAINT fk_favorito_imovel      FOREIGN KEY (imovel_id) REFERENCES imoveis (id)
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role       FOREIGN KEY (role_id)       REFERENCES roles       (id),
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions (id)
);
